# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://bigdoglabs.com'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Big Dog Labs
# Description of the Site
description: Technology and Code for the Big Dogs
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/bigdoglabs_heroimage.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: mike@mikehathaway.com
facebook_username: mikehathaway
#twitter_username: thedevslot
#instagram_username: thedevslot
linkedin_username: hathawaymike
github_username:  mjh2901
youtube_channel_id: UCYt_ge-HCo601quPuyrNrng
reddit_username: mjh2901
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
#google-analytics: UA-163806439-1

# Disqus
disqus-shortname: mjh2901

# Name of the Author
author-name: Big Dog Labs
# URL for the Image of the Author
author-image: /assets/images/bigdoglabs_logo.png
# 60 Words About the Author
author-about: A technology company dedicated to providing innovative solutions and services to help businesses thrive in the digital age. Our team of experts specializes in software development, IT consulting, and digital transformation strategies.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/mjh2901

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/