name: Build and deploy Jekyll site

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: bundle exec jekyll build --destination _site

    - name: Deploy to gh-pages using SSH deploy key
      env:
        REPO: ${{ github.repository }}
        COMMIT_MSG: "Deploy site from ${GITHUB_SHA}"
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    - name: Push built site to gh-pages via SSH
      env:
        REPO: ${{ github.repository }}
        COMMIT_MSG: "Deploy site from ${GITHUB_SHA}"
      run: |
        set -euo pipefail
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        TMPDIR=$(mktemp -d)
        echo "Using temp dir: ${TMPDIR}"
        cd "${TMPDIR}"

        git init
        git remote add origin git@github.com:${REPO}.git

        if git ls-remote --exit-code --heads origin gh-pages; then
          git fetch --depth=1 origin gh-pages
          git checkout -b gh-pages FETCH_HEAD
        else
          git checkout --orphan gh-pages
        fi

        git rm -rf . || true
        rsync -a --delete "${GITHUB_WORKSPACE}/_site/" ./

        if [ -z "$(git status --porcelain)" ]; then
          echo "No changes to deploy"
          exit 0
        fi

        git add -A
        git commit -m "${COMMIT_MSG}"
        git push --force origin gh-pages
        echo "Deployed to gh-pages via SSH"
