name: Build and deploy Jekyll site

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: bundle exec jekyll build --destination _site

    - name: Upload artifact for GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./_site

    - name: Deploy to gh-pages branch via GITHUB_TOKEN
      env:
        REPO: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MSG: "Deploy site from ${GITHUB_SHA}"
      run: |
        set -e
        echo "Preparing deploy to gh-pages"
        # Clone the repo using the token for authentication
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git clone --depth=1 https://x-access-token:${GH_TOKEN}@github.com/${REPO} repo
        cd repo

        # Create or switch to gh-pages branch
        if git show-ref --quiet refs/heads/gh-pages; then
          git checkout gh-pages
        else
          git checkout --orphan gh-pages
          git rm -rf . || true
        fi

        # Copy generated site into repo
        rsync -a --delete ../_site/ .

        # If no changes, exit
        if git status --porcelain | grep .; then
          git add -A
          git commit -m "${COMMIT_MSG}"
          git push --force origin gh-pages
          echo "Deployed to gh-pages"
        else
          echo "No changes to deploy"
        fi
